#ifndef AXIOM_SDK_SYSCALL_H
#define AXIOM_SDK_SYSCALL_H
#define AXIOM_SYSCALL_ABI_VERSION 1
enum axiom_syscall{SYS_ABI_VERSION,SYS_GETPID,SYS_GETUID,SYS_YIELD,SYS_SLEEP,SYS_EXIT,SYS_WRITE,SYS_KEY_POLL,SYS_COMMAND,SYS_SPAWN,SYS_SERVICE_HEARTBEAT,SYS_COUNT};
#endif
