#include "account.h"
#include "acpi.h"
#include "hardware.h"
#include "log.h"
#include "vfs.h"
#include <stddef.h>
#include <stdint.h>

#define DB_MAGIC 0x4143434f554e5453ull
#define DB_VERSION 2u
#define DB_PATH "/system/config/accounts.db"
#define DB_BACKUP "/system/config/accounts.bak"
#define DB_TEMP "/system/config/accounts.tmp"

struct account_record {struct account_info info;uint64_t salt,verifier;uint32_t failures;uint64_t retry_at;};
struct group_record {struct group_info info;};
struct db_header {uint64_t magic;uint32_t version,account_count,next_uid,group_count;uint64_t checksum;};

static struct account_record records[ACCOUNT_MAX];
static struct group_record groups[GROUP_MAX];
static uint32_t used,next_uid,groups_used;
static int session=-1;
static uint64_t work[8192];
static volatile uint8_t account_lock;
static char recovery_key_once[33];

static void lock(void){while(__atomic_test_and_set(&account_lock,__ATOMIC_ACQUIRE))__asm__ volatile("pause");}
static void unlock(void){__atomic_clear(&account_lock,__ATOMIC_RELEASE);}
static bool equal(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return *a==*b;}
static size_t length(const char*s){size_t n=0;while(s&&s[n])n++;return n;}
static void copy(char*d,const char*s,size_t cap){size_t i=0;if(!cap)return;while(s&&s[i]&&i+1<cap){d[i]=s[i];i++;}d[i]=0;}
static void append(char*d,const char*s,size_t cap){size_t n=length(d);copy(d+n,s,cap>n?cap-n:0);}
static uint64_t mix(uint64_t x){x^=x>>30;x*=0xbf58476d1ce4e5b9ull;x^=x>>27;x*=0x94d049bb133111ebull;return x^(x>>31);}
static uint64_t password_hash(const char*p,uint64_t salt){uint64_t x=mix(salt^0xa7105ec0deull);for(size_t i=0;p[i];i++)x=mix(x^(uint8_t)p[i]^(i<<24));for(uint32_t i=0;i<8192;i++)work[i]=x=mix(x+i+salt);for(uint32_t round=0;round<3;round++)for(uint32_t i=0;i<8192;i++){uint32_t j=(uint32_t)(x^work[i])&8191;x=mix(x+work[j]+i);work[i]^=x;}uint64_t out=mix(x^work[x&8191]);for(uint32_t i=0;i<8192;i++)work[i]=0;return out;}
static void make_recovery_key(char*out){static const char hex[]="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";uint64_t a=entropy_seed(),b=entropy_seed()^hardware_uptime_ms();for(uint32_t i=0;i<32;i++){a=mix(a+b+i);b=mix(b+a+(i<<8));out[i]=hex[(a^b)&31];}out[32]=0;}
static int find_name(const char*n){for(uint32_t i=0;i<used;i++)if(equal(records[i].info.name,n))return(int)i;return-1;}
static int find_uid(uint32_t uid){for(uint32_t i=0;i<used;i++)if(records[i].info.uid==uid)return(int)i;return-1;}
static int find_group(const char*n){for(uint32_t i=0;i<groups_used;i++)if(equal(groups[i].info.name,n))return(int)i;return-1;}
static bool valid_name(const char*n){size_t size=length(n);if(size<2||size>=32)return false;for(size_t i=0;i<size;i++)if(!((n[i]>='a'&&n[i]<='z')||(i&&n[i]>='0'&&n[i]<='9')||n[i]=='-'))return false;return true;}
static uint64_t checksum(const void*data,size_t size,uint64_t value){const uint8_t*p=data;for(size_t i=0;i<size;i++){value^=p[i];value*=1099511628211ull;}return value;}
static void add_builtin_group(const char*name,uint32_t gid){struct group_info*g=&groups[groups_used++].info;*g=(struct group_info){.gid=gid};copy(g->name,name,sizeof(g->name));}
static void group_add_uid(int index,uint32_t uid){struct group_info*g=&groups[index].info;for(uint32_t i=0;i<g->member_count;i++)if(g->members[i]==uid)return;if(g->member_count<ACCOUNT_MAX)g->members[g->member_count++]=uid;}
static void group_remove_uid(int index,uint32_t uid){struct group_info*g=&groups[index].info;for(uint32_t i=0;i<g->member_count;i++)if(g->members[i]==uid){for(uint32_t j=i+1;j<g->member_count;j++)g->members[j-1]=g->members[j];g->member_count--;return;}}
static void default_environment(struct account_info*i){i->creation_mask=0022;copy(i->path,"/system/bin:/apps",sizeof(i->path));copy(i->locale,"en_US",sizeof(i->locale));copy(i->timezone,"UTC",sizeof(i->timezone));copy(i->startup,"/system/bin/init",sizeof(i->startup));copy(i->home,"/users/",sizeof(i->home));append(i->home,i->name,sizeof(i->home));}
static void assign_default_groups(struct account_info*i){int users=find_group("users"),admin=find_group("admin"),services=find_group("services");if(i->type==ACCOUNT_ADMIN){i->gid=100;if(admin>=0)group_add_uid(admin,i->uid);if(users>=0)group_add_uid(users,i->uid);}else if(i->type==ACCOUNT_SERVICE){i->gid=200;if(services>=0)group_add_uid(services,i->uid);}else{i->gid=1000;if(users>=0)group_add_uid(users,i->uid);}}
static void root_context(struct vfs_security_context*saved){vfs_capture_security_context(saved);vfs_set_security_context(0,0,0,0,0022,~0ull);}
static bool write_db(const char*path){struct db_header h={DB_MAGIC,DB_VERSION,used,next_uid,groups_used,0};h.checksum=checksum(&h,sizeof(h),1469598103934665603ull);h.checksum=checksum(records,used*sizeof(records[0]),h.checksum);h.checksum=checksum(groups,groups_used*sizeof(groups[0]),h.checksum);int fd=vfs_open(path,VFS_WRITE|VFS_CREATE|VFS_TRUNCATE);if(fd<0)return false;bool ok=vfs_write(fd,&h,sizeof(h))==(long)sizeof(h)&&vfs_write(fd,records,used*sizeof(records[0]))==(long)(used*sizeof(records[0]))&&vfs_write(fd,groups,groups_used*sizeof(groups[0]))==(long)(groups_used*sizeof(groups[0]));vfs_close(fd);if(ok)vfs_chmod(path,0600);return ok;}
static bool validate_loaded(const struct account_record*a,uint32_t ac,const struct group_record*g,uint32_t gc){if(!ac||ac>ACCOUNT_MAX||!gc||gc>GROUP_MAX||a[0].info.uid!=0||a[0].info.type!=ACCOUNT_RECOVERY)return false;for(uint32_t i=0;i<ac;i++){if(i&&(!valid_name(a[i].info.name)||a[i].info.uid<1000))return false;for(uint32_t j=i+1;j<ac;j++)if(a[i].info.uid==a[j].info.uid||equal(a[i].info.name,a[j].info.name))return false;}for(uint32_t i=0;i<gc;i++){if(!valid_name(g[i].info.name)||g[i].info.member_count>ACCOUNT_MAX)return false;for(uint32_t j=i+1;j<gc;j++)if(g[i].info.gid==g[j].info.gid||equal(g[i].info.name,g[j].info.name))return false;for(uint32_t m=0;m<g[i].info.member_count;m++){bool found=false;for(uint32_t u=0;u<ac;u++)if(a[u].info.uid==g[i].info.members[m])found=true;if(!found)return false;}}return true;}
static bool read_db(const char*path,struct account_record*a,struct group_record*g,struct db_header*out){int fd=vfs_open(path,VFS_READ);if(fd<0)return false;struct db_header h;bool ok=vfs_read(fd,&h,sizeof(h))==(long)sizeof(h)&&h.magic==DB_MAGIC&&h.version==DB_VERSION&&h.account_count<=ACCOUNT_MAX&&h.group_count<=GROUP_MAX&&vfs_read(fd,a,h.account_count*sizeof(a[0]))==(long)(h.account_count*sizeof(a[0]))&&vfs_read(fd,g,h.group_count*sizeof(g[0]))==(long)(h.group_count*sizeof(g[0]));vfs_close(fd);if(!ok)return false;uint64_t expected=h.checksum;h.checksum=0;uint64_t sum=checksum(&h,sizeof(h),1469598103934665603ull);sum=checksum(a,h.account_count*sizeof(a[0]),sum);sum=checksum(g,h.group_count*sizeof(g[0]),sum);if(sum!=expected||!validate_loaded(a,h.account_count,g,h.group_count))return false;h.checksum=expected;*out=h;return true;}

void account_audit(const char*event,const char*detail){log_write("AUDIT",event);struct vfs_security_context saved;root_context(&saved);int e=vfs_mkdir("/var/log",0700);(void)e;struct vfs_stat st;uint64_t offset=vfs_stat_path("/var/log/security.log",&st)?0:st.size;int fd=vfs_open("/var/log/security.log",VFS_WRITE|VFS_CREATE);if(fd>=0){char line[224],number[24];line[0]=0;uint64_t value=hardware_uptime_ms(),divisor=1;while(value/divisor>=10)divisor*=10;size_t n=0;do{number[n++]=(char)('0'+(value/divisor)%10);divisor/=10;}while(divisor);number[n]=0;append(line,number,sizeof(line));append(line," uid=",sizeof(line));value=session>=0?records[session].info.uid:0;divisor=1;while(value/divisor>=10)divisor*=10;n=0;do{number[n++]=(char)('0'+(value/divisor)%10);divisor/=10;}while(divisor);number[n]=0;append(line,number,sizeof(line));append(line," ",sizeof(line));append(line,event,sizeof(line));if(detail&&*detail){append(line," ",sizeof(line));append(line,detail,sizeof(line));}append(line,"\n",sizeof(line));vfs_seek(fd,offset);vfs_write(fd,line,length(line));vfs_close(fd);vfs_chmod("/var/log/security.log",0600);}vfs_restore_security_context(&saved);}
long account_read_audit(void*buffer,uint64_t offset,uint32_t size){if(!buffer||size>4096)return-1;struct vfs_security_context saved;root_context(&saved);int fd=vfs_open("/var/log/security.log",VFS_READ);long result=fd<0?fd:(vfs_seek(fd,offset)<0?-1:vfs_read(fd,buffer,size));if(fd>=0)vfs_close(fd);vfs_restore_security_context(&saved);return result;}

void account_init(void){used=1;next_uid=1000;groups_used=0;session=-1;account_lock=0;add_builtin_group("recovery",0);add_builtin_group("admin",100);add_builtin_group("services",200);add_builtin_group("devices",300);add_builtin_group("users",1000);records[0]=(struct account_record){.info={.uid=0,.gid=0,.creation_mask=0077,.type=ACCOUNT_RECOVERY,.enabled=true,.configured=false,.name="recovery",.home="/system/recovery",.path="/system/bin",.locale="en_US",.timezone="UTC",.startup="/system/bin/recovery"},.salt=entropy_seed()};group_add_uid(0,0);vfs_set_credentials(0,0);}
bool account_prepare_recovery(void){make_recovery_key(recovery_key_once);records[0].salt=entropy_seed();records[0].verifier=password_hash(recovery_key_once,records[0].salt);records[0].info.configured=true;struct vfs_security_context saved;root_context(&saved);vfs_mkdir("/system/recovery",0700);vfs_restore_security_context(&saved);return true;}
bool account_take_recovery_key(char*out,uint32_t capacity){if(!out||capacity<33||!recovery_key_once[0])return false;copy(out,recovery_key_once,capacity);for(uint32_t i=0;i<sizeof(recovery_key_once);i++)recovery_key_once[i]=0;return true;}
bool account_rotate_recovery_key(char*out,uint32_t capacity){if(!out||capacity<33)return false;make_recovery_key(recovery_key_once);records[0].salt=entropy_seed();records[0].verifier=password_hash(recovery_key_once,records[0].salt);records[0].failures=0;records[0].retry_at=0;records[0].info.configured=true;bool ok=account_save();if(ok)ok=account_take_recovery_key(out,capacity);account_audit(ok?"recovery-key-rotated":"recovery-key-rotation-failed","");return ok;}
bool account_recovery_self_test(void){return recovery_key_once[0]&&account_authenticate("recovery",recovery_key_once,UINT64_MAX/2)==0;}
int account_create(const char*n,const char*p,enum account_type type,uint32_t*uid){size_t pl=length(p);if(!valid_name(n)||pl<8||pl>72||type==ACCOUNT_RECOVERY)return-1;lock();if(used>=ACCOUNT_MAX||find_name(n)>=0){unlock();return-1;}struct account_record*r=&records[used++];*r=(struct account_record){.info={.uid=next_uid++,.type=type,.enabled=true,.configured=true},.salt=entropy_seed()};copy(r->info.name,n,sizeof(r->info.name));default_environment(&r->info);assign_default_groups(&r->info);r->verifier=password_hash(p,r->salt);if(uid)*uid=r->info.uid;struct vfs_security_context saved;root_context(&saved);vfs_mkdir(r->info.home,0700);vfs_chown(r->info.home,r->info.uid,r->info.gid);vfs_restore_security_context(&saved);unlock();account_audit("account-create",n);return 0;}
int account_create_service(const char*n,uint32_t*uid){if(!valid_name(n))return-1;lock();if(used>=ACCOUNT_MAX||find_name(n)>=0){unlock();return-1;}struct account_record*r=&records[used++];*r=(struct account_record){.info={.uid=next_uid++,.type=ACCOUNT_SERVICE,.enabled=true,.configured=false},.salt=entropy_seed()};copy(r->info.name,n,sizeof(r->info.name));default_environment(&r->info);assign_default_groups(&r->info);copy(r->info.home,"/var/lib/",sizeof(r->info.home));append(r->info.home,n,sizeof(r->info.home));if(uid)*uid=r->info.uid;struct vfs_security_context saved;root_context(&saved);vfs_mkdir("/var/lib",0755);vfs_mkdir(r->info.home,0700);vfs_chown(r->info.home,r->info.uid,r->info.gid);vfs_restore_security_context(&saved);unlock();account_audit("service-account-create",n);return 0;}
int account_authenticate(const char*n,const char*p,uint64_t now){lock();int i=find_name(n);if(i<0){unlock();account_audit("login-failed","unknown-account");return-1;}struct account_record*r=&records[i];if(!r->info.enabled||!r->info.configured||now<r->retry_at){unlock();account_audit("login-blocked",n);return-1;}uint64_t got=password_hash(p,r->salt),difference=got^r->verifier;difference|=(uint64_t)-(int64_t)difference;if(difference>>63){if(r->failures<8)r->failures++;uint64_t delay=250ull<<(r->failures>5?5:r->failures);r->retry_at=now+delay;unlock();account_audit("login-failed",n);return-1;}r->failures=0;r->retry_at=0;int uid=(int)r->info.uid;unlock();return uid;}
int account_disable(const char*n,bool disabled){lock();int i=find_name(n);if(i<=0){unlock();return-1;}records[i].info.enabled=!disabled;if(session==i&&disabled)session=-1;unlock();account_audit(disabled?"account-disabled":"account-enabled",n);return 0;}
int account_remove(const char*n){lock();int i=find_name(n);if(i<=0||session==i){unlock();return-1;}uint32_t uid=records[i].info.uid;for(uint32_t g=0;g<groups_used;g++)group_remove_uid((int)g,uid);for(uint32_t x=(uint32_t)i+1;x<used;x++)records[x-1]=records[x];used--;unlock();account_audit("account-remove",n);return 0;}
int account_set_password(const char*n,const char*p){size_t size=length(p);if(size<8||size>72)return-1;lock();int i=find_name(n);if(i<0){unlock();return-1;}records[i].salt=entropy_seed();records[i].verifier=password_hash(p,records[i].salt);records[i].info.configured=true;records[i].failures=0;records[i].retry_at=0;unlock();account_audit("password-change",n);return 0;}
int account_set_type(const char*n,enum account_type type){if(type==ACCOUNT_RECOVERY)return-1;lock();int i=find_name(n);if(i<=0){unlock();return-1;}uint32_t uid=records[i].info.uid;int admin=find_group("admin"),services=find_group("services"),users=find_group("users");if(admin>=0)group_remove_uid(admin,uid);if(services>=0)group_remove_uid(services,uid);if(users>=0)group_remove_uid(users,uid);records[i].info.type=type;assign_default_groups(&records[i].info);unlock();account_audit("account-role-change",n);return 0;}
int account_group_create(const char*n,uint32_t gid){if(!valid_name(n)||gid<100||groups_used>=GROUP_MAX)return-1;lock();if(find_group(n)>=0){unlock();return-1;}for(uint32_t i=0;i<groups_used;i++)if(groups[i].info.gid==gid){unlock();return-1;}struct group_info*g=&groups[groups_used++].info;*g=(struct group_info){.gid=gid};copy(g->name,n,sizeof(g->name));unlock();account_audit("group-create",n);return 0;}
int account_group_add(const char*g,const char*u){lock();int gi=find_group(g),ui=find_name(u);if(gi<0||ui<0||groups[gi].info.member_count>=ACCOUNT_MAX){unlock();return-1;}group_add_uid(gi,records[ui].info.uid);unlock();account_audit("group-add",u);return 0;}
int account_group_remove(const char*g,const char*u){lock();int gi=find_group(g),ui=find_name(u);if(gi<0||ui<=0||records[ui].info.gid==groups[gi].info.gid){unlock();return-1;}group_remove_uid(gi,records[ui].info.uid);unlock();account_audit("group-remove",u);return 0;}
const struct group_info*account_group_at(uint32_t i){return i<groups_used?&groups[i].info:0;}
uint32_t account_group_count(void){return groups_used;}
uint32_t account_groups_for_uid(uint32_t uid,uint32_t*out,uint32_t capacity){uint32_t count=0;for(uint32_t g=0;g<groups_used;g++)for(uint32_t m=0;m<groups[g].info.member_count;m++)if(groups[g].info.members[m]==uid){if(count<capacity)out[count]=groups[g].info.gid;count++;break;}return count;}
bool account_is_admin(uint32_t uid){int user=find_uid(uid),g=find_group("admin");if(user<0||g<0||!records[user].info.enabled||!records[user].info.configured||records[user].info.type!=ACCOUNT_ADMIN)return false;for(uint32_t i=0;i<groups[g].info.member_count;i++)if(groups[g].info.members[i]==uid)return true;return false;}
bool account_verify_current_password(const char*p,uint64_t now){if(session<0)return false;char name[32];copy(name,records[session].info.name,sizeof(name));return account_authenticate(name,p,now)==(int)records[session].info.uid;}
int account_set_environment(const char*n,const char*k,const char*v){int i=find_name(n);if(i<0||length(v)>95)return-1;struct account_info*a=&records[i].info;if(equal(k,"PATH"))copy(a->path,v,sizeof(a->path));else if(equal(k,"LOCALE"))copy(a->locale,v,sizeof(a->locale));else if(equal(k,"TIMEZONE"))copy(a->timezone,v,sizeof(a->timezone));else if(equal(k,"STARTUP"))copy(a->startup,v,sizeof(a->startup));else if(equal(k,"UMASK")){uint32_t m=0;for(size_t x=0;v[x]>='0'&&v[x]<='7';x++)m=m*8+(uint32_t)(v[x]-'0');a->creation_mask=m&0777;}else return-1;account_audit("environment-change",k);return 0;}
const char*account_get_environment(const struct account_info*a,const char*k){if(!a)return 0;if(equal(k,"HOME"))return a->home;if(equal(k,"PATH"))return a->path;if(equal(k,"LOCALE"))return a->locale;if(equal(k,"TIMEZONE"))return a->timezone;if(equal(k,"STARTUP"))return a->startup;return 0;}
bool account_save(void){lock();struct vfs_security_context saved;root_context(&saved);int e=vfs_mkdir("/system/config",0700);bool ok=(e==0||e==VFS_EEXIST)&&write_db(DB_TEMP);if(ok){struct vfs_stat st;vfs_unlink(DB_BACKUP,false);if(vfs_stat_path(DB_PATH,&st)==0)vfs_rename(DB_PATH,DB_BACKUP);ok=vfs_rename(DB_TEMP,DB_PATH)==0;if(!ok)vfs_rename(DB_BACKUP,DB_PATH);}vfs_restore_security_context(&saved);unlock();return ok;}
bool account_load(void){lock();struct vfs_security_context saved;root_context(&saved);struct account_record a[ACCOUNT_MAX];struct group_record g[GROUP_MAX];struct db_header h;bool ok=read_db(DB_PATH,a,g,&h)||read_db(DB_BACKUP,a,g,&h);if(ok){for(uint32_t i=0;i<h.account_count;i++){records[i]=a[i];records[i].failures=0;records[i].retry_at=0;}for(uint32_t i=0;i<h.group_count;i++)groups[i]=g[i];used=h.account_count;next_uid=h.next_uid;groups_used=h.group_count;session=-1;}vfs_restore_security_context(&saved);unlock();return ok;}
bool account_has_admin(void){for(uint32_t i=1;i<used;i++)if(records[i].info.enabled&&records[i].info.configured&&account_is_admin(records[i].info.uid))return true;return false;}
bool account_begin_session(uint32_t uid){int i=find_uid(uid);if(i<0||!records[i].info.enabled)return false;session=i;uint32_t list[ACCOUNT_GROUP_MAX],count=account_groups_for_uid(uid,list,ACCOUNT_GROUP_MAX);vfs_set_security_context(records[i].info.uid,records[i].info.gid,list,count,records[i].info.creation_mask,0);account_audit("login-success",records[i].info.name);return true;}
void account_end_session(void){if(session>=0)account_audit("logout",records[session].info.name);session=-1;vfs_set_credentials(0,0);}
const struct account_info*account_current(void){return session<0?0:&records[session].info;}
const struct account_info*account_at(uint32_t i){return i<used?&records[i].info:0;}
const struct account_info*account_named(const char*n){int i=find_name(n);return i<0?0:&records[i].info;}
uint32_t account_count(void){return used;}
const char*account_type_name(enum account_type type){static const char*names[]={"standard","admin","service","recovery"};return type<=ACCOUNT_RECOVERY?names[type]:"invalid";}
bool account_self_test(void){struct account_record saved[ACCOUNT_MAX];struct group_record saved_groups[GROUP_MAX];struct vfs_security_context saved_context;vfs_capture_security_context(&saved_context);int saved_session=session;for(uint32_t i=0;i<used;i++)saved[i]=records[i];for(uint32_t i=0;i<groups_used;i++)saved_groups[i]=groups[i];uint32_t saved_used=used,saved_next=next_uid,saved_group_count=groups_used;bool ok=true;uint32_t uid;if(account_create("test-user","correct-horse",ACCOUNT_STANDARD,&uid)||uid<1000)ok=false;if(account_authenticate("test-user","wrong-pass",0)>=0)ok=false;if(account_authenticate("test-user","correct-horse",100000)!=(int)uid)ok=false;if(!account_begin_session(uid)||!account_current()||account_current()->uid!=uid)ok=false;if(account_groups_for_uid(uid,0,0)==0)ok=false;account_end_session();if(account_disable("test-user",true)||account_authenticate("test-user","correct-horse",200000)>=0)ok=false;if(!account_save()||!account_load()||account_count()!=saved_used+1)ok=false;if(account_remove("test-user")||account_count()!=saved_used)ok=false;for(uint32_t i=0;i<saved_used;i++)records[i]=saved[i];for(uint32_t i=0;i<saved_group_count;i++)groups[i]=saved_groups[i];used=saved_used;next_uid=saved_next;groups_used=saved_group_count;session=saved_session;vfs_restore_security_context(&saved_context);return ok;}
bool account_database_recovery_self_test(void){struct account_record saved[ACCOUNT_MAX];struct group_record saved_groups[GROUP_MAX];struct vfs_security_context context;vfs_capture_security_context(&context);int saved_session=session;uint32_t saved_used=used,saved_next=next_uid,saved_group_count=groups_used;for(uint32_t i=0;i<used;i++)saved[i]=records[i];for(uint32_t i=0;i<groups_used;i++)saved_groups[i]=groups[i];bool ok=account_save()&&account_save();struct vfs_security_context root;root_context(&root);int fd=vfs_open(DB_PATH,VFS_WRITE|VFS_TRUNCATE);uint64_t corruption=0xdeadbeefbad0c0deull;if(fd<0||vfs_write(fd,&corruption,sizeof(corruption))!=(long)sizeof(corruption))ok=false;if(fd>=0)vfs_close(fd);vfs_restore_security_context(&root);if(!account_load()||used!=saved_used)ok=false;for(uint32_t i=0;i<saved_used;i++)records[i]=saved[i];for(uint32_t i=0;i<saved_group_count;i++)groups[i]=saved_groups[i];used=saved_used;next_uid=saved_next;groups_used=saved_group_count;session=saved_session;if(!account_save())ok=false;vfs_restore_security_context(&context);return ok;}
