#include "filesystems.h"
#include "hardware.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#define AX_MAGIC 0x5346584d4f495841ull
#define AX_JOURNAL 0x4c4e524a4d4f4958ull
#define AX_VERSION 2u
#define AX_INODES 64u
#define AX_INODE_START 4u
#define AX_DATA_START 36u
#define AX_INODE_MAGIC 0x444f4e49u
#define AX_FILE 1u
#define AX_DIRECTORY 2u
#define AX_HARDLINK 3u
#define AX_SYMLINK 4u
struct ax_super{uint64_t magic;uint32_t version,block_size;uint64_t sectors,created,generation;uint32_t inode_count,inode_start,data_start,features,checksum;uint8_t reserved[452];};
struct ax_journal{uint64_t magic,generation,target;uint32_t state,payload_checksum,header_checksum;uint8_t reserved[476];};
struct ax_inode{uint32_t magic;uint16_t mode,type;uint32_t uid,gid,links,flags;uint64_t size,created,modified,direct[8];uint32_t parent,generation;char name[64],xattr_name[24],xattr_value[48];};
static uint32_t hash(const void*data,size_t size){const uint8_t*p=data;uint32_t h=2166136261u;while(size--)h=(h^*p++)*16777619u;return h;}
static size_t len(const char*s){size_t n=0;while(s[n])n++;return n;}static bool eq(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return!*a&&!*b;}static void strcopy(char*d,const char*s,size_t n){if(!n)return;while(*s&&n>1){*d++=*s++;n--;}*d=0;}
static int read_sector(struct axiomfs_volume*v,uint64_t sector,void*b){return sector<v->sectors?block_read(v->device,v->start_lba+sector,1,b):-1;}
static int write_raw(struct axiomfs_volume*v,uint64_t sector,const void*b){return sector<v->sectors?block_write(v->device,v->start_lba+sector,1,b):-1;}
static int metadata_write(struct axiomfs_volume*v,uint64_t target,const uint8_t*payload){struct ax_journal j={.magic=AX_JOURNAL,.generation=++v->generation,.target=target,.state=1,.payload_checksum=hash(payload,512)};j.header_checksum=hash(&j,32);uint8_t zero[512]={0};if(write_raw(v,2,payload)||block_flush(v->device)||write_raw(v,1,&j)||block_flush(v->device)||write_raw(v,target,payload)||block_flush(v->device)||write_raw(v,1,zero)||block_flush(v->device))return-1;return 0;}
static int replay(struct axiomfs_volume*v,bool repair){struct ax_journal j;uint8_t payload[512],zero[512]={0};if(read_sector(v,1,&j))return-1;if(!j.state)return 0;if(j.magic!=AX_JOURNAL||j.target>=v->sectors||read_sector(v,2,payload)||hash(payload,512)!=j.payload_checksum)return-1;if(!repair||v->device->readonly)return-2;if(write_raw(v,j.target,payload)||block_flush(v->device)||write_raw(v,1,zero)||block_flush(v->device))return-1;v->generation=j.generation;return 0;}
static int inode_read(struct axiomfs_volume*v,uint32_t number,struct ax_inode*out){if(number>=v->inode_count)return-1;uint8_t sector[512];if(read_sector(v,AX_INODE_START+number/2,sector))return-1;*out=((struct ax_inode*)sector)[number&1];return 0;}
static int inode_write(struct axiomfs_volume*v,uint32_t number,const struct ax_inode*in){if(number>=v->inode_count)return-1;uint8_t sector[512];uint64_t target=AX_INODE_START+number/2;if(read_sector(v,target,sector))return-1;((struct ax_inode*)sector)[number&1]=*in;return metadata_write(v,target,sector);}
static bool allowed(const struct ax_inode*i,uint32_t uid,uint32_t gid,uint16_t wanted){if(uid==0)return true;uint16_t bits=uid==i->uid?(i->mode>>6):(gid==i->gid?(i->mode>>3):i->mode);return(bits&wanted)==wanted;}
static int child(struct axiomfs_volume*v,uint32_t parent,const char*name,uint32_t*out){for(uint32_t n=1;n<v->inode_count;n++){struct ax_inode i;if(inode_read(v,n,&i))return-1;if(i.magic==AX_INODE_MAGIC&&i.parent==parent&&eq(i.name,name)){*out=i.type==AX_HARDLINK?(uint32_t)i.direct[0]:n;return 0;}}return-1;}
static int resolve(struct axiomfs_volume*v,const char*path,uint32_t*out){if(!path||!*path)return-1;while(*path=='/')path++;uint32_t at=0;if(!*path){*out=0;return 0;}char part[64];while(*path){size_t n=0;while(*path&&*path!='/'&&n<63)part[n++]=*path++;part[n]=0;while(*path=='/')path++;if(child(v,at,part,&at))return-1;}struct ax_inode i;if(inode_read(v,at,&i))return-1;if(i.type==AX_SYMLINK)return resolve(v,i.xattr_value,out);*out=at;return 0;}
static int split_parent(struct axiomfs_volume*v,const char*path,uint32_t*parent,char*name){char temp[256];strcopy(temp,path,sizeof(temp));size_t n=len(temp);while(n>1&&temp[n-1]=='/')temp[--n]=0;char*slash=0;for(char*p=temp;*p;p++)if(*p=='/')slash=p;if(!slash){strcopy(name,temp,64);*parent=0;return 0;}strcopy(name,slash+1,64);if(slash==temp){*parent=0;return 0;}*slash=0;return resolve(v,temp,parent);}
static int bitmap_update(struct axiomfs_volume*v,uint32_t block,bool used){uint8_t map[512];if(block>=4096||read_sector(v,3,map))return-1;uint8_t mask=1u<<(block&7);if(used)map[block>>3]|=mask;else map[block>>3]&=(uint8_t)~mask;return metadata_write(v,3,map);}
static int allocate_block(struct axiomfs_volume*v,uint32_t*out){uint8_t map[512],zero[512]={0};if(read_sector(v,3,map))return-1;uint32_t limit=v->sectors>4096?4096:(uint32_t)v->sectors;for(uint32_t b=v->data_start;b<limit;b++)if(!(map[b>>3]&(1u<<(b&7)))){if(bitmap_update(v,b,true)||write_raw(v,b,zero)||block_flush(v->device))return-1;*out=b;return 0;}return-1;}
int axiomfs_format(struct block_device*d,uint64_t start,uint64_t sectors){if(!d||d->readonly||d->sector_size!=512||sectors<128||sectors>4096)return-1;struct axiomfs_volume v={.device=d,.start_lba=start,.sectors=sectors,.generation=1,.inode_count=AX_INODES,.data_start=AX_DATA_START};uint8_t zero[512]={0};for(uint32_t s=1;s<AX_DATA_START;s++)if(write_raw(&v,s,zero))return-1;uint8_t map[512]={0};for(uint32_t b=0;b<AX_DATA_START;b++)map[b>>3]|=1u<<(b&7);if(write_raw(&v,3,map))return-1;struct ax_inode root={.magic=AX_INODE_MAGIC,.mode=0755,.type=AX_DIRECTORY,.links=1,.created=hardware_uptime_ms()/1000,.modified=hardware_uptime_ms()/1000};root.name[0]='/';if(inode_write(&v,0,&root))return-1;struct ax_super s={.magic=AX_MAGIC,.version=AX_VERSION,.block_size=512,.sectors=sectors,.created=root.created,.generation=v.generation,.inode_count=AX_INODES,.inode_start=AX_INODE_START,.data_start=AX_DATA_START,.features=0x7f};s.checksum=hash(&s,56);if(write_raw(&v,0,&s)||block_flush(d))return-1;return 0;}
int axiomfs_open(struct axiomfs_volume*v,struct block_device*d,uint64_t start,bool repair){struct ax_super s;if(!v||!d||block_read(d,start,1,&s)||s.magic!=AX_MAGIC||s.version!=AX_VERSION||s.block_size!=512||s.sectors<128||s.sectors>d->sectors-start||s.inode_count!=AX_INODES||s.data_start!=AX_DATA_START||s.checksum!=hash(&s,56))return-1;*v=(struct axiomfs_volume){.device=d,.start_lba=start,.sectors=s.sectors,.generation=s.generation,.inode_count=s.inode_count,.data_start=s.data_start};return replay(v,repair);}
int axiomfs_check(struct block_device*d,uint64_t start,bool repair){struct axiomfs_volume v;int e=axiomfs_open(&v,d,start,repair);if(e)return e;uint8_t expected[512]={0},actual[512];for(uint32_t b=0;b<v.data_start;b++)expected[b>>3]|=1u<<(b&7);for(uint32_t n=0;n<v.inode_count;n++){struct ax_inode i;if(inode_read(&v,n,&i))return-1;if(!i.magic)continue;bool invalid=i.magic!=AX_INODE_MAGIC||i.parent>=v.inode_count||i.type<AX_FILE||i.type>AX_SYMLINK;if(!invalid&&i.type==AX_HARDLINK){struct ax_inode target;invalid=i.direct[0]>=v.inode_count||inode_read(&v,(uint32_t)i.direct[0],&target)||target.magic!=AX_INODE_MAGIC;}if(invalid){if(!repair||d->readonly)return-1;struct ax_inode zero={0};if(inode_write(&v,n,&zero))return-1;continue;}if(i.type==AX_FILE)for(unsigned k=0;k<8;k++)if(i.direct[k]){if(i.direct[k]<v.data_start||i.direct[k]>=v.sectors)return-1;uint8_t mask=1u<<(i.direct[k]&7);if(expected[i.direct[k]>>3]&mask)return-1;expected[i.direct[k]>>3]|=mask;}}if(read_sector(&v,3,actual))return-1;bool mismatch=false;for(unsigned i=0;i<512;i++)if(actual[i]!=expected[i]){mismatch=true;break;}if(mismatch){if(!repair||d->readonly)return-3;return metadata_write(&v,3,expected);}return 0;}
int axiomfs_create(struct axiomfs_volume*v,const char*path,bool directory,uint32_t uid,uint32_t gid,uint32_t mode){uint32_t parent;char name[64];if(split_parent(v,path,&parent,name)||!name[0])return-1;uint32_t existing;if(!child(v,parent,name,&existing))return-2;struct ax_inode p;if(inode_read(v,parent,&p)||p.type!=AX_DIRECTORY||!allowed(&p,uid,gid,2))return-3;for(uint32_t n=1;n<v->inode_count;n++){struct ax_inode i;if(inode_read(v,n,&i))return-1;if(!i.magic){i=(struct ax_inode){.magic=AX_INODE_MAGIC,.mode=mode&0777,.type=directory?AX_DIRECTORY:AX_FILE,.uid=uid,.gid=gid,.links=1,.parent=parent,.created=hardware_uptime_ms()/1000,.modified=hardware_uptime_ms()/1000};strcopy(i.name,name,sizeof(i.name));return inode_write(v,n,&i);}}return-4;}
long axiomfs_write(struct axiomfs_volume*v,const char*path,uint64_t offset,const void*buffer,size_t size,uint32_t uid,uint32_t gid){uint32_t n;if(resolve(v,path,&n))return-1;struct ax_inode i;if(inode_read(v,n,&i)||i.type!=AX_FILE||!allowed(&i,uid,gid,2)||offset+size>4096)return-1;uint64_t owned=0;for(uint32_t x=0;x<v->inode_count;x++){struct ax_inode q;if(!inode_read(v,x,&q)&&q.magic==AX_INODE_MAGIC&&q.uid==uid)owned+=q.size;}if(offset+size>i.size&&owned+(offset+size-i.size)>1024*1024)return-5;const uint8_t*in=buffer;size_t done=0;while(done<size){unsigned slot=(offset+done)/512,inside=(offset+done)%512;if(!i.direct[slot]){uint32_t block;if(allocate_block(v,&block))return done?(long)done:-4;i.direct[slot]=block;}uint8_t sector[512];if(read_sector(v,i.direct[slot],sector))return-1;size_t amount=512-inside;if(amount>size-done)amount=size-done;for(size_t x=0;x<amount;x++)sector[inside+x]=in[done+x];if(write_raw(v,i.direct[slot],sector)||block_flush(v->device))return-1;done+=amount;}if(offset+done>i.size)i.size=offset+done;i.modified=hardware_uptime_ms()/1000;i.generation++;return inode_write(v,n,&i)?-1:(long)done;}
long axiomfs_read(struct axiomfs_volume*v,const char*path,uint64_t offset,void*buffer,size_t size,uint32_t uid,uint32_t gid){uint32_t n;if(resolve(v,path,&n))return-1;struct ax_inode i;if(inode_read(v,n,&i)||i.type!=AX_FILE||!allowed(&i,uid,gid,4)||offset>i.size)return-1;if(size>i.size-offset)size=i.size-offset;uint8_t*out=buffer;size_t done=0;while(done<size){unsigned slot=(offset+done)/512,inside=(offset+done)%512;size_t amount=512-inside;if(amount>size-done)amount=size-done;if(!i.direct[slot])for(size_t x=0;x<amount;x++)out[done+x]=0;else{uint8_t sector[512];if(read_sector(v,i.direct[slot],sector))return-1;for(size_t x=0;x<amount;x++)out[done+x]=sector[inside+x];}done+=amount;}return(long)done;}
int axiomfs_stat_path(struct axiomfs_volume*v,const char*path,struct axiomfs_stat*s){uint32_t n;if(resolve(v,path,&n))return-1;struct ax_inode i;if(inode_read(v,n,&i))return-1;*s=(struct axiomfs_stat){.size=i.size,.created=i.created,.modified=i.modified,.inode=n,.uid=i.uid,.gid=i.gid,.mode=i.mode,.links=i.links,.directory=i.type==AX_DIRECTORY,.symlink=i.type==AX_SYMLINK};for(unsigned x=0;x<8;x++)if(!i.direct[x]&&i.size>(uint64_t)x*512)s->sparse=true;return 0;}
int axiomfs_rename(struct axiomfs_volume*v,const char*old,const char*newpath){uint32_t n,parent;char name[64];if(resolve(v,old,&n)||split_parent(v,newpath,&parent,name))return-1;uint32_t exists;if(!child(v,parent,name,&exists))return-2;struct ax_inode i;if(inode_read(v,n,&i))return-1;i.parent=parent;strcopy(i.name,name,sizeof(i.name));i.modified=hardware_uptime_ms()/1000;return inode_write(v,n,&i);}
int axiomfs_link(struct axiomfs_volume*v,const char*target,const char*link_path,bool symbolic){uint32_t target_inode,parent;char name[64];if(resolve(v,target,&target_inode)||split_parent(v,link_path,&parent,name))return-1;for(uint32_t n=1;n<v->inode_count;n++){struct ax_inode i;if(inode_read(v,n,&i))return-1;if(!i.magic){i=(struct ax_inode){.magic=AX_INODE_MAGIC,.mode=0777,.type=symbolic?AX_SYMLINK:AX_HARDLINK,.links=1,.parent=parent};strcopy(i.name,name,sizeof(i.name));if(symbolic)strcopy(i.xattr_value,target,sizeof(i.xattr_value));else{i.direct[0]=target_inode;struct ax_inode t;if(inode_read(v,target_inode,&t))return-1;t.links++;if(inode_write(v,target_inode,&t))return-1;}return inode_write(v,n,&i);}}return-1;}
int axiomfs_set_xattr(struct axiomfs_volume*v,const char*path,const char*name,const char*value){uint32_t n;if(resolve(v,path,&n)||len(name)>=24||len(value)>=48)return-1;struct ax_inode i;if(inode_read(v,n,&i))return-1;strcopy(i.xattr_name,name,sizeof(i.xattr_name));strcopy(i.xattr_value,value,sizeof(i.xattr_value));return inode_write(v,n,&i);}
int axiomfs_get_xattr(struct axiomfs_volume*v,const char*path,const char*name,char*value,size_t cap){uint32_t n;if(resolve(v,path,&n))return-1;struct ax_inode i;if(inode_read(v,n,&i)||!eq(i.xattr_name,name))return-1;strcopy(value,i.xattr_value,cap);return 0;}
int axiomfs_simulate_interrupted_write(struct block_device*d,uint64_t start){struct axiomfs_volume v;if(axiomfs_open(&v,d,start,false))return-1;uint8_t payload[512];if(read_sector(&v,3,payload))return-1;payload[511]^=1;struct ax_journal j={.magic=AX_JOURNAL,.generation=v.generation+1,.target=3,.state=1,.payload_checksum=hash(payload,512)};j.header_checksum=hash(&j,32);return write_raw(&v,2,payload)||block_flush(d)||write_raw(&v,1,&j)||block_flush(d)?-1:0;}
bool axiomfs_self_test(struct block_device*d){if(axiomfs_format(d,0,128))return false;struct axiomfs_volume v;if(axiomfs_open(&v,d,0,false)||axiomfs_create(&v,"/users",true,0,0,0755)||axiomfs_create(&v,"/users/admin",true,0,0,0700)||axiomfs_create(&v,"/users/admin/test.txt",false,0,0,0600))return false;const char*text="AXIOMFS";if(axiomfs_write(&v,"/users/admin/test.txt",1024,text,7,0,0)!=7)return false;char out[8]={0};if(axiomfs_read(&v,"/users/admin/test.txt",1024,out,7,0,0)!=7)return false;for(unsigned i=0;i<7;i++)if(out[i]!=text[i])return false;struct axiomfs_stat st;if(axiomfs_stat_path(&v,"/users/admin/test.txt",&st)||!st.sparse||st.size!=1031)return false;if(axiomfs_set_xattr(&v,"/users/admin/test.txt","user.kind","test"))return false;char value[16];if(axiomfs_get_xattr(&v,"/users/admin/test.txt","user.kind",value,sizeof(value))||!eq(value,"test"))return false;if(axiomfs_rename(&v,"/users/admin/test.txt","/users/admin/moved.txt")||axiomfs_link(&v,"/users/admin/moved.txt","/users/admin/link.txt",false)||axiomfs_check(d,0,false))return false;
 uint8_t page[512]={0};char path[16]="/fill00";for(unsigned file=0;file<12;file++){path[5]=(char)('0'+file/10);path[6]=(char)('0'+file%10);if(axiomfs_create(&v,path,false,0,0,0600))return false;for(unsigned block=0;block<8;block++){long written=axiomfs_write(&v,path,(uint64_t)block*512,page,512,0,0);if(file<11&&written!=512)return false;if(file==11&&block<3&&written!=512)return false;if(file==11&&block==3&&written>=0)break;}}
 if(axiomfs_create(&v,"/overflow",false,0,0,0600)||axiomfs_write(&v,"/overflow",0,page,1,0,0)>=0)return false;
 if(axiomfs_check(d,0,false))return false;
 uint32_t damaged;if(resolve(&v,"/fill00",&damaged))return false;struct ax_inode inode;if(inode_read(&v,damaged,&inode))return false;inode.parent=999;if(inode_write(&v,damaged,&inode)||axiomfs_check(d,0,false)==0||axiomfs_check(d,0,true))return false;return true;}
