#include "block.h"
#include "memory.h"
static struct block_device devices[BLOCK_MAX_DEVICES];static uint32_t device_count;static struct block_partition parts[BLOCK_MAX_PARTITIONS];static uint32_t part_count;
struct cache_line{bool valid,dirty;struct block_device*device;uint64_t lba,age;uint8_t data[512];};static struct cache_line cache[32];static uint64_t clock;
static bool eq(const uint8_t*a,const char*b,unsigned n){for(unsigned i=0;i<n;i++)if(a[i]!=(uint8_t)b[i])return false;return true;}
void block_init(void){device_count=part_count=0;for(unsigned i=0;i<32;i++)cache[i].valid=false;}
int block_register(const struct block_device*d){if(device_count>=BLOCK_MAX_DEVICES||!d||!d->read||!d->sector_size)return-1;devices[device_count]=*d;return device_count++;}
uint32_t block_device_count(void){return device_count;}struct block_device*block_device_at(uint32_t i){return i<device_count?&devices[i]:0;}
struct block_device*block_find(const char*name){for(uint32_t i=0;i<device_count;i++){const char*a=devices[i].name,*b=name;while(*a&&*a==*b){a++;b++;}if(!*a&&!*b)return&devices[i];}return 0;}
static int raw_read(struct block_device*d,uint64_t l,uint32_t c,void*b){if(!d||!d->present||l+c>d->sectors)return-1;return d->read(d,l,c,b);}
int block_read(struct block_device*d,uint64_t l,uint32_t count,void*buffer){if(d->sector_size!=512)return raw_read(d,l,count,buffer);uint8_t*out=buffer;for(uint32_t n=0;n<count;n++){struct cache_line*x=0,*old=&cache[0];for(unsigned i=0;i<32;i++){if(cache[i].valid&&cache[i].device==d&&cache[i].lba==l+n){x=&cache[i];break;}if(!cache[i].valid||cache[i].age<old->age)old=&cache[i];}if(!x){x=old;if(x->dirty&&(!x->device->present||!x->device->write||x->device->write(x->device,x->lba,1,x->data)))return-1;if(raw_read(d,l+n,1,x->data))return-1;x->valid=true;x->dirty=false;x->device=d;x->lba=l+n;}x->age=++clock;for(unsigned i=0;i<512;i++)out[n*512+i]=x->data[i];}return 0;}
int block_write(struct block_device*d,uint64_t l,uint32_t count,const void*buffer){if(!d||d->readonly||!d->write||!d->present||l+count>d->sectors)return-1;if(d->sector_size!=512)return d->write(d,l,count,(void*)buffer);const uint8_t*in=buffer;for(uint32_t n=0;n<count;n++){struct cache_line*line=0,*old=&cache[0];for(unsigned i=0;i<32;i++){if(cache[i].valid&&cache[i].device==d&&cache[i].lba==l+n){line=&cache[i];break;}if(!cache[i].valid||cache[i].age<old->age)old=&cache[i];}if(!line){line=old;if(line->dirty&&(!line->device->present||!line->device->write||line->device->write(line->device,line->lba,1,line->data)))return-1;}line->valid=true;line->dirty=true;line->device=d;line->lba=l+n;line->age=++clock;for(unsigned i=0;i<512;i++)line->data[i]=in[n*512+i];}return 0;}
int block_flush(struct block_device*d){int e=0;for(unsigned i=0;i<32;i++)if(cache[i].valid&&cache[i].dirty&&cache[i].device==d){if(!d->present||d->write(d,cache[i].lba,1,cache[i].data))e=-1;else cache[i].dirty=false;}return e;}
int block_flush_all(void){int error=0;for(uint32_t i=0;i<device_count;i++)if(block_flush(&devices[i]))error=-1;return error;}
static uint32_t le32(const uint8_t*p){return p[0]|p[1]<<8|p[2]<<16|p[3]<<24;}static uint64_t le64(const uint8_t*p){return le32(p)|(uint64_t)le32(p+4)<<32;}
void block_scan_partitions(void){part_count=0;uint8_t sector[512];for(uint32_t d=0;d<device_count&&part_count<BLOCK_MAX_PARTITIONS;d++){if(block_read(&devices[d],0,1,sector))continue;if(sector[510]!=0x55||sector[511]!=0xaa)continue;bool protective=sector[450]==0xee;if(protective&&!block_read(&devices[d],1,1,sector)&&eq(sector,"EFI PART",8)){uint64_t entries=le64(sector+72);uint32_t number=le32(sector+80),size=le32(sector+84);if(size>=128&&size<=512){for(uint32_t i=0;i<number&&part_count<BLOCK_MAX_PARTITIONS;i++){uint64_t byte=(uint64_t)i*size,lba=entries+byte/512;if(block_read(&devices[d],lba,1,sector))break;uint8_t*e=sector+byte%512;if(!le64(e))continue;struct block_partition*p=&parts[part_count];p->device=&devices[d];p->first_lba=le64(e+32);p->sectors=le64(e+40)-p->first_lba+1;p->gpt=true;p->type=0xee;p->name[0]='p';p->name[1]='0'+(++part_count%10);p->name[2]=0;}}}else for(unsigned i=0;i<4&&part_count<BLOCK_MAX_PARTITIONS;i++){uint8_t*e=sector+446+i*16;if(!e[4])continue;struct block_partition*p=&parts[part_count];p->device=&devices[d];p->first_lba=le32(e+8);p->sectors=le32(e+12);p->type=e[4];p->gpt=false;p->name[0]='p';p->name[1]='0'+(++part_count%10);p->name[2]=0;}}}
uint32_t block_partition_count(void){return part_count;}const struct block_partition*block_partition_at(uint32_t i){return i<part_count?&parts[i]:0;}
