#include "config.h"
#include "hardware.h"
#include "log.h"
#include "security.h"
#include "vfs.h"
#include <stddef.h>

#define SYSTEM_SCHEMA 2u
#define USER_SCHEMA 1u
static struct config_document system_config, user_config;
static char user_path[160];
static uint32_t user_uid, user_gid;
static bool user_loaded;
static const char *system_path = "/system/config/system.conf";

static size_t length(const char *s){size_t n=0;while(s&&s[n])n++;return n;}
static bool equal(const char*a,const char*b){if(!a||!b)return false;while(*a&&*a==*b){a++;b++;}return!*a&&!*b;}
static void copy(char*d,const char*s,size_t cap){size_t n=0;if(!cap)return;while(s&&s[n]&&n+1<cap){d[n]=s[n];n++;}d[n]=0;}
static bool append(char*d,const char*s,size_t cap){size_t a=length(d),b=length(s);if(a+b+1>cap)return false;copy(d+a,s,cap-a);return true;}
static bool key_valid(const char*k){size_t n=length(k);if(!n||n>=40)return false;for(size_t i=0;i<n;i++)if(!((k[i]>='a'&&k[i]<='z')||(k[i]>='0'&&k[i]<='9')||k[i]=='.'||k[i]=='-'||k[i]=='_'))return false;return true;}
static bool value_valid(const char*v){size_t n=length(v);if(n>=128)return false;for(size_t i=0;i<n;i++)if((uint8_t)v[i]<32||v[i]=='=')return false;return true;}
static uint32_t decimal(const char*s){uint32_t v=0;if(!s||!*s)return 0;while(*s){if(*s<'0'||*s>'9'||v>429496729u)return 0;v=v*10+(uint32_t)(*s++-'0');}return v;}
static void number(uint32_t value,char*out){char r[12];uint32_t n=0;do{r[n++]=(char)('0'+value%10);value/=10;}while(value);for(uint32_t i=0;i<n;i++)out[i]=r[n-i-1];out[n]=0;}
static void root(struct vfs_security_context*saved){vfs_capture_security_context(saved);vfs_set_security_context(0,0,0,0,0022,CAP_ALL);}

void config_clear(struct config_document*d,uint32_t schema){if(d)*d=(struct config_document){.schema=schema};}
const char*config_get(const struct config_document*d,const char*k){if(!d||!k)return 0;for(uint32_t i=0;i<d->count;i++)if(equal(d->entries[i].key,k))return d->entries[i].value;return 0;}
bool config_set(struct config_document*d,const char*k,const char*v){if(!d||!key_valid(k)||!value_valid(v))return false;for(uint32_t i=0;i<d->count;i++)if(equal(d->entries[i].key,k)){copy(d->entries[i].value,v,sizeof(d->entries[i].value));return true;}if(d->count>=CONFIG_ENTRY_MAX)return false;copy(d->entries[d->count].key,k,sizeof(d->entries[d->count].key));copy(d->entries[d->count].value,v,sizeof(d->entries[d->count].value));d->count++;return true;}

static bool parse(const char*text,struct config_document*d){config_clear(d,0);while(*text){while(*text=='\n'||*text=='\r'||*text==' '||*text=='\t')text++;if(!*text)break;if(*text=='#'){while(*text&&*text!='\n')text++;continue;}char k[40],v[128];uint32_t kn=0,vn=0;while(*text&&*text!='='&&*text!='\n'&&*text!='\r'){if(kn+1>=sizeof(k))return false;k[kn++]=*text++;}k[kn]=0;if(*text!='=')return false;text++;while(*text&&*text!='\n'&&*text!='\r'){if(vn+1>=sizeof(v))return false;v[vn++]=*text++;}v[vn]=0;if(config_get(d,k)||!config_set(d,k,v))return false;while(*text=='\n'||*text=='\r')text++;}d->schema=decimal(config_get(d,"schema"));return d->schema>0;}
static bool read_path(const char*path,struct config_document*d){int fd=vfs_open(path,VFS_READ);if(fd<0)return false;char text[4096];long n=vfs_read(fd,text,sizeof(text)-1);vfs_close(fd);if(n<=0)return false;text[n]=0;return parse(text,d);}
static bool variant(const char*path,const char*suffix,char*out,size_t cap){if(length(path)+length(suffix)+1>cap)return false;copy(out,path,cap);return append(out,suffix,cap);}

bool config_save_atomic(const char*path,const struct config_document*d){if(!path||!d||!d->schema)return false;struct vfs_security_context saved;root(&saved);char temp[160],backup[160];bool ok=variant(path,".tmp",temp,sizeof(temp))&&variant(path,".bak",backup,sizeof(backup));char text[4096],schema[12];size_t at=0;number(d->schema,schema);const char*prefix="schema=";for(size_t i=0;prefix[i];i++)text[at++]=prefix[i];for(size_t i=0;schema[i];i++)text[at++]=schema[i];text[at++]='\n';for(uint32_t e=0;e<d->count&&ok;e++){const struct config_entry*x=&d->entries[e];if(equal(x->key,"schema"))continue;size_t need=length(x->key)+length(x->value)+2;if(at+need>=sizeof(text)){ok=false;break;}for(size_t i=0;x->key[i];i++)text[at++]=x->key[i];text[at++]='=';for(size_t i=0;x->value[i];i++)text[at++]=x->value[i];text[at++]='\n';}if(ok){int fd=vfs_open(temp,VFS_WRITE|VFS_CREATE|VFS_TRUNCATE);ok=fd>=0&&vfs_write(fd,text,at)==(long)at;if(fd>=0)vfs_close(fd);}if(ok){struct vfs_stat st;vfs_unlink(backup,false);if(vfs_stat_path(path,&st)==0)ok=vfs_rename(path,backup)==0;if(ok)ok=vfs_rename(temp,path)==0;if(!ok){vfs_unlink(path,false);vfs_rename(backup,path);}else vfs_chmod(path,0600);}vfs_restore_security_context(&saved);return ok;}

bool config_load(const char*path,uint32_t expected,const struct config_document*defaults,struct config_document*d){if(!path||!expected||!d)return false;struct vfs_security_context saved;root(&saved);struct config_document loaded;bool primary=read_path(path,&loaded),backup_used=false;if(!primary){char backup[160];if(variant(path,".bak",backup,sizeof(backup)))backup_used=read_path(backup,&loaded);}vfs_restore_security_context(&saved);if(!primary&&!backup_used){if(!defaults)return false;loaded=*defaults;}if(!loaded.schema||loaded.schema>expected)return false;bool save=!primary||backup_used||loaded.schema<expected;if(defaults)for(uint32_t i=0;i<defaults->count;i++)if(!config_get(&loaded,defaults->entries[i].key)){if(!config_set(&loaded,defaults->entries[i].key,defaults->entries[i].value))return false;save=true;}loaded.schema=expected;*d=loaded;return!save||config_save_atomic(path,d);}

static bool one_of(const char*v,const char*a,const char*b,const char*c){return equal(v,a)||(b&&equal(v,b))||(c&&equal(v,c));}
static bool simple(const char*v,bool slash){size_t n=length(v);if(!n||n>63)return false;for(size_t i=0;i<n;i++){char c=v[i];if(!((c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9')||c=='-'||c=='_'||c=='.'||(slash&&c=='/')))return false;}return true;}
static bool system_valid(const char*k,const char*v){if(equal(k,"hostname"))return simple(v,false);if(equal(k,"locale")||equal(k,"timezone"))return simple(v,true);if(equal(k,"keyboard"))return one_of(v,"us","dvorak",0);if(equal(k,"display.scale"))return one_of(v,"1","2","3");if(equal(k,"power.policy"))return one_of(v,"balanced","performance","powersave");return false;}
static bool user_valid(const char*k,const char*v){if(equal(k,"locale")||equal(k,"timezone"))return simple(v,true);if(equal(k,"keyboard"))return one_of(v,"inherit","us","dvorak");if(equal(k,"display.scale"))return one_of(v,"inherit","1","2")||equal(v,"3");if(equal(k,"theme"))return one_of(v,"dark","light",0);if(equal(k,"startup"))return v[0]=='/'&&simple(v,true);return false;}

bool config_system_apply(void){const char*layout=config_get(&system_config,"keyboard");if(!layout||!keyboard_set_layout(layout))return false;LOG_INFO("validated system settings applied");return true;}
bool config_system_init(void){struct vfs_security_context saved;root(&saved);int e=vfs_mkdir("/system/config",0700);vfs_restore_security_context(&saved);if(e&&e!=VFS_EEXIST)return false;struct config_document defaults;config_clear(&defaults,SYSTEM_SCHEMA);config_set(&defaults,"hostname","axiom");config_set(&defaults,"locale","en_US");config_set(&defaults,"timezone","UTC");config_set(&defaults,"keyboard","us");config_set(&defaults,"display.scale","1");config_set(&defaults,"power.policy","balanced");if(!config_load(system_path,SYSTEM_SCHEMA,&defaults,&system_config))return false;for(uint32_t i=0;i<system_config.count;i++){const struct config_entry*x=&system_config.entries[i];if(!equal(x->key,"schema")&&!system_valid(x->key,x->value))return false;}return config_system_apply();}
const struct config_document*config_system(void){return&system_config;}
bool config_system_set(const char*k,const char*v){if(!system_valid(k,v))return false;struct config_document changed=system_config;if(!config_set(&changed,k,v)||!config_save_atomic(system_path,&changed))return false;system_config=changed;return config_system_apply();}

static bool user_directory(const char*name,char*out,size_t cap){if(!simple(name,false))return false;copy(out,"/users/",cap);return append(out,name,cap)&&append(out,"/.config",cap);}
bool config_user_init(const char*name,uint32_t uid,uint32_t gid){char dir[144];if(!user_directory(name,dir,sizeof(dir)))return false;copy(user_path,dir,sizeof(user_path));if(!append(user_path,"/session.conf",sizeof(user_path)))return false;struct vfs_security_context saved;root(&saved);int e=vfs_mkdir(dir,0700);bool ok=e==0||e==VFS_EEXIST;if(ok){vfs_chown(dir,uid,gid);vfs_chmod(dir,0700);}vfs_restore_security_context(&saved);if(!ok)return false;struct config_document defaults;config_clear(&defaults,USER_SCHEMA);config_set(&defaults,"locale","en_US");config_set(&defaults,"timezone","UTC");config_set(&defaults,"keyboard","inherit");config_set(&defaults,"display.scale","inherit");config_set(&defaults,"theme","dark");config_set(&defaults,"startup","/system/bin/init");if(!config_load(user_path,USER_SCHEMA,&defaults,&user_config))return false;for(uint32_t i=0;i<user_config.count;i++){const struct config_entry*x=&user_config.entries[i];if(!equal(x->key,"schema")&&!user_valid(x->key,x->value))return false;}root(&saved);vfs_chown(user_path,uid,gid);vfs_chmod(user_path,0600);vfs_restore_security_context(&saved);user_uid=uid;user_gid=gid;user_loaded=true;const char*layout=config_get(&user_config,"keyboard");return!layout||equal(layout,"inherit")||keyboard_set_layout(layout);}
void config_user_end(void){user_loaded=false;user_path[0]=0;config_clear(&user_config,USER_SCHEMA);config_system_apply();}
const struct config_document*config_user(void){return user_loaded?&user_config:0;}
bool config_user_set(const char*k,const char*v){if(!user_loaded||!user_valid(k,v))return false;struct config_document changed=user_config;if(!config_set(&changed,k,v)||!config_save_atomic(user_path,&changed))return false;struct vfs_security_context saved;root(&saved);vfs_chown(user_path,user_uid,user_gid);vfs_chmod(user_path,0600);vfs_restore_security_context(&saved);user_config=changed;return!equal(k,"keyboard")||equal(v,"inherit")||keyboard_set_layout(v);}

bool config_self_test(void){struct config_document defaults,old,loaded,future;config_clear(&defaults,2);config_set(&defaults,"required","safe");config_clear(&old,1);config_set(&old,"legacy","yes");if(!config_save_atomic("/tmp/config-test",&old)||!config_load("/tmp/config-test",2,&defaults,&loaded))return false;bool ok=loaded.schema==2&&equal(config_get(&loaded,"legacy"),"yes")&&equal(config_get(&loaded,"required"),"safe");struct vfs_security_context saved;root(&saved);int fd=vfs_open("/tmp/config-test",VFS_WRITE|VFS_TRUNCATE);uint64_t bad=0xdecafbaddecafbadull;if(fd<0||vfs_write(fd,&bad,sizeof(bad))!=(long)sizeof(bad))ok=false;if(fd>=0)vfs_close(fd);vfs_restore_security_context(&saved);ok=ok&&config_load("/tmp/config-test",2,&defaults,&loaded)&&equal(config_get(&loaded,"legacy"),"yes");config_clear(&future,3);config_set(&future,"required","unsafe");ok=ok&&config_save_atomic("/tmp/config-future",&future)&&!config_load("/tmp/config-future",2,&defaults,&loaded)&&!config_set(&loaded,"Bad Key","value")&&!config_set(&loaded,"valid","line\nbreak");root(&saved);vfs_unlink("/tmp/config-test",false);vfs_unlink("/tmp/config-test.bak",false);vfs_unlink("/tmp/config-test.tmp",false);vfs_unlink("/tmp/config-future",false);vfs_unlink("/tmp/config-future.bak",false);vfs_restore_security_context(&saved);return ok;}
