#include "device.h"
#include "block.h"
#include "hardware.h"
#include "log.h"
#include "pci.h"
#include "security.h"
#include "vfs.h"
#include <stddef.h>

static struct managed_device devices[DEVICE_MANAGER_MAX];
static struct device_event events[DEVICE_EVENT_MAX];
static uint32_t used, event_used, event_next;
static uint64_t generation, event_sequence;

static size_t length(const char*s){size_t n=0;while(s&&s[n])n++;return n;}
static bool equal(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return!*a&&!*b;}
static void copy(char*d,const char*s,size_t cap){size_t n=0;if(!cap)return;while(s&&s[n]&&n+1<cap){d[n]=s[n];n++;}d[n]=0;}
static void append(char*d,const char*s,size_t cap){size_t n=length(d);copy(d+n,s,n<cap?cap-n:0);}
static void decimal(uint64_t v,char*out,size_t cap){char r[24];size_t n=0;do{r[n++]=(char)('0'+v%10);v/=10;}while(v&&n<sizeof(r));size_t at=0;while(n&&at+1<cap)out[at++]=r[--n];out[at]=0;}
static void hex(uint32_t v,unsigned digits,char*out){static const char h[]="0123456789abcdef";for(unsigned i=0;i<digits;i++)out[i]=h[(v>>((digits-i-1)*4))&15];out[digits]=0;}
static void root(struct vfs_security_context*saved){vfs_capture_security_context(saved);vfs_set_security_context(0,0,0,0,0022,CAP_ALL);}
static int find(const char*name){for(uint32_t i=0;i<used;i++)if(equal(devices[i].stable_name,name))return(int)i;return-1;}
static void event(enum device_event_type type,const char*name){struct device_event*e=&events[event_next++%DEVICE_EVENT_MAX];*e=(struct device_event){.sequence=++event_sequence,.time_ms=hardware_uptime_ms(),.type=type};copy(e->stable_name,name,sizeof(e->stable_name));if(event_used<DEVICE_EVENT_MAX)event_used++;}
static bool write_node(struct managed_device*d){struct vfs_security_context saved;root(&saved);int fd=vfs_open(d->path,VFS_WRITE|VFS_CREATE|VFS_TRUNCATE);bool ok=fd>=0&&vfs_write(fd,d->description,length(d->description))==(long)length(d->description);if(fd>=0)vfs_close(fd);if(ok)ok=vfs_chown(d->path,d->uid,d->gid)==0&&vfs_chmod(d->path,d->mode)==0;vfs_restore_security_context(&saved);return ok;}
static bool candidate(const char*name,const char*path,const char*kind,const char*description){int index=find(name);bool new_slot=index<0;if(new_slot){if(used>=DEVICE_MANAGER_MAX)return false;index=(int)used++;devices[index]=(struct managed_device){.uid=0,.gid=300,.mode=0640};copy(devices[index].stable_name,name,sizeof(devices[index].stable_name));copy(devices[index].path,path,sizeof(devices[index].path));copy(devices[index].kind,kind,sizeof(devices[index].kind));}struct managed_device*d=&devices[index];bool appeared=new_slot||!d->present,changed=!appeared&&!equal(d->description,description);copy(d->description,description,sizeof(d->description));d->present=true;d->generation=generation;if((appeared||changed)&&!write_node(d))return false;if(appeared)event(DEVICE_ADDED,name);else if(changed)event(DEVICE_CHANGED,name);return true;}

bool device_manager_scan(void){generation++;bool ok=true;for(uint32_t i=0;i<block_device_count();i++){struct block_device*b=block_device_at(i);char stable[48]="block/",path[96]="/devices/block/",description[96]="name=";append(stable,b->name,sizeof(stable));append(path,b->name,sizeof(path));append(description,b->name,sizeof(description));append(description," model=",sizeof(description));append(description,b->model,sizeof(description));append(description," sectors=",sizeof(description));char n[24];decimal(b->sectors,n,sizeof(n));append(description,n,sizeof(description));append(description,b->readonly?" readonly\n":" writable\n",sizeof(description));if(!candidate(stable,path,"block",description))ok=false;}for(uint32_t i=0;i<pci_device_count();i++){const struct pci_device*p=pci_device_at(i);char b[12],s[12],f[12],vendor[12],device[12];hex(p->bus,2,b);hex(p->slot,2,s);hex(p->function,1,f);hex(p->vendor_id,4,vendor);hex(p->device_id,4,device);char stable[48]="pci/0000:",path[96]="/devices/pci/0000:",description[96]="vendor=0x";append(stable,b,sizeof(stable));append(stable,":",sizeof(stable));append(stable,s,sizeof(stable));append(stable,".",sizeof(stable));append(stable,f,sizeof(stable));append(path,b,sizeof(path));append(path,":",sizeof(path));append(path,s,sizeof(path));append(path,".",sizeof(path));append(path,f,sizeof(path));append(description,vendor,sizeof(description));append(description," device=0x",sizeof(description));append(description,device,sizeof(description));append(description," class=0x",sizeof(description));hex(p->class_code,2,b);append(description,b,sizeof(description));append(description,"\n",sizeof(description));if(!candidate(stable,path,"pci",description))ok=false;}for(uint32_t i=0;i<used;i++)if(devices[i].present&&devices[i].generation!=generation){devices[i].present=false;event(DEVICE_REMOVED,devices[i].stable_name);struct vfs_security_context saved;root(&saved);vfs_unlink(devices[i].path,false);vfs_restore_security_context(&saved);}return ok;}

bool device_manager_init(void){used=event_used=event_next=0;generation=event_sequence=0;struct vfs_security_context saved;root(&saved);int block=vfs_mkdir("/devices/block",0750),pci=vfs_mkdir("/devices/pci",0750);bool ok=(block==0||block==VFS_EEXIST)&&(pci==0||pci==VFS_EEXIST);if(ok){vfs_chown("/devices",0,300);vfs_chmod("/devices",0750);vfs_chown("/devices/block",0,300);vfs_chmod("/devices/block",0750);vfs_chown("/devices/pci",0,300);vfs_chmod("/devices/pci",0750);}vfs_restore_security_context(&saved);if(!ok)return false;ok=device_manager_scan();if(ok)LOG_INFO("stable device namespace and hotplug event queue online");return ok;}
uint32_t device_manager_count(void){uint32_t count=0;for(uint32_t i=0;i<used;i++)if(devices[i].present)count++;return count;}
const struct managed_device*device_manager_at(uint32_t index){uint32_t seen=0;for(uint32_t i=0;i<used;i++)if(devices[i].present){if(seen++==index)return&devices[i];}return 0;}
uint32_t device_event_count(void){return event_used;}
const struct device_event*device_event_at(uint32_t index){if(index>=event_used)return 0;uint32_t start=(event_next+DEVICE_EVENT_MAX-event_used)%DEVICE_EVENT_MAX;return&events[(start+index)%DEVICE_EVENT_MAX];}
const char*device_event_type_name(enum device_event_type type){static const char*names[]={"add","change","remove"};return type<=DEVICE_REMOVED?names[type]:"invalid";}
bool device_manager_self_test(void){uint32_t expected=block_device_count()+pci_device_count();if(device_manager_count()!=expected||event_used<expected)return false;uint64_t before=event_sequence;if(!device_manager_scan()||event_sequence!=before)return false;for(uint32_t i=0;i<device_manager_count();i++){const struct managed_device*d=device_manager_at(i);struct vfs_stat st;if(!d||vfs_stat_path(d->path,&st)||st.uid!=0||st.gid!=300||st.mode!=0640||!d->present)return false;for(uint32_t j=i+1;j<device_manager_count();j++)if(equal(d->stable_name,device_manager_at(j)->stable_name))return false;}if(!candidate("test/hotplug0","/devices/test-hotplug0","test","synthetic hotplug probe\n"))return false;int probe=find("test/hotplug0");struct vfs_stat st;if(probe<0||vfs_stat_path("/devices/test-hotplug0",&st)||st.gid!=300||st.mode!=0640)return false;before=event_sequence;if(!device_manager_scan()||event_sequence!=before+1||devices[probe].present||vfs_stat_path("/devices/test-hotplug0",&st)!=VFS_ENOENT)return false;const struct device_event*removed=device_event_at(device_event_count()-1);return removed&&removed->type==DEVICE_REMOVED&&equal(removed->stable_name,"test/hotplug0")&&device_manager_count()==expected;}
