#include "filesystems.h"
#include <stdint.h>
#include <stddef.h>
#define FAT_EOC 0x0ffffff8u
static uint16_t le16f(const uint8_t*p){return(uint16_t)p[0]|(uint16_t)p[1]<<8;}static uint32_t le32f(const uint8_t*p){return(uint32_t)le16f(p)|(uint32_t)le16f(p+2)<<16;}
static char upper(char c){return c>='a'&&c<='z'?(char)(c-'a'+'A'):c;}static bool same(const char*a,const char*b){while(*a&&*b){if(upper(*a++)!=upper(*b++))return false;}return!*a&&!*b;}
static void copy(char*d,const char*s,size_t cap){if(!cap)return;while(*s&&cap>1){*d++=*s++;cap--;}*d=0;}
int fat32_open(struct fat32_volume*v,struct block_device*d,uint64_t start){uint8_t b[512];if(!v||!d||d->sector_size!=512||block_read(d,start,1,b))return-1;uint16_t bytes=le16f(b+11),reserved=le16f(b+14);uint8_t spc=b[13],fats=b[16];uint32_t spf=le32f(b+36),root=le32f(b+44),total=le16f(b+19);if(!total)total=le32f(b+32);if(bytes!=512||!spc||(spc&(spc-1))||!reserved||!fats||!spf||root<2||b[510]!=0x55||b[511]!=0xaa)return-1;uint64_t data=(uint64_t)reserved+(uint64_t)fats*spf;if(total<=data)return-1;*v=(struct fat32_volume){.device=d,.start_lba=start,.total_sectors=total,.fat_lba=start+reserved,.data_lba=start+data,.sectors_per_fat=spf,.root_cluster=root,.cluster_count=(total-data)/spc,.bytes_per_sector=bytes,.sectors_per_cluster=spc,.fat_count=fats};return 0;}
int fat32_validate(struct block_device*d,uint64_t start){struct fat32_volume v;return fat32_open(&v,d,start);}
static uint64_t cluster_lba(const struct fat32_volume*v,uint32_t cluster){return v->data_lba+(uint64_t)(cluster-2)*v->sectors_per_cluster;}
static int next_cluster(struct fat32_volume*v,uint32_t cluster,uint32_t*next){uint8_t b[512];uint64_t offset=(uint64_t)cluster*4;if(block_read(v->device,v->fat_lba+offset/512,1,b))return-1;*next=le32f(b+offset%512)&0x0fffffff;return 0;}
static void short_name(const uint8_t*e,char*out){unsigned n=0;for(unsigned i=0;i<8&&e[i]!=' ';i++)out[n++]=(char)e[i];if(e[8]!=' '){out[n++]='.';for(unsigned i=8;i<11&&e[i]!=' ';i++)out[n++]=(char)e[i];}out[n]=0;}
static void lfn_piece(const uint8_t*e,char*name){unsigned order=(e[0]&31);if(!order||order>20)return;unsigned at=(order-1)*13;static const uint8_t pos[13]={1,3,5,7,9,14,16,18,20,22,24,28,30};for(unsigned i=0;i<13&&at+i<255;i++){uint16_t c=le16f(e+pos[i]);if(c==0){name[at+i]=0;break;}if(c==0xffff)continue;name[at+i]=c<128?(char)c:'?';}}
typedef bool(*scan_fn)(const struct fat32_entry*,void*);
static int scan_directory(struct fat32_volume*v,uint32_t cluster,scan_fn callback,void*context){uint8_t sector[512];char long_name[256]={0};uint32_t visited=0;while(cluster>=2&&cluster<FAT_EOC&&visited++<=v->cluster_count){for(uint8_t s=0;s<v->sectors_per_cluster;s++){if(block_read(v->device,cluster_lba(v,cluster)+s,1,sector))return-1;for(unsigned off=0;off<512;off+=32){const uint8_t*e=sector+off;if(e[0]==0)return 0;if(e[0]==0xe5){long_name[0]=0;continue;}if(e[11]==0x0f){if(e[0]&0x40)for(unsigned z=0;z<256;z++)long_name[z]=0;lfn_piece(e,long_name);continue;}if(e[11]&0x08){long_name[0]=0;continue;}struct fat32_entry item={.cluster=(uint32_t)le16f(e+20)<<16|le16f(e+26),.size=le32f(e+28),.date=le16f(e+24),.time=le16f(e+22),.directory=!!(e[11]&0x10),.readonly=!!(e[11]&1),.hidden=!!(e[11]&2)};if(long_name[0])copy(item.name,long_name,sizeof(item.name));else short_name(e,item.name);long_name[0]=0;if(!callback(&item,context))return 1;}}uint32_t next;if(next_cluster(v,cluster,&next))return-1;if(next==cluster)return-1;cluster=next;}return cluster>=FAT_EOC?0:-1;}
struct find_context{const char*name;struct fat32_entry*result;bool found;};static bool find_cb(const struct fat32_entry*e,void*c){struct find_context*f=c;if(same(e->name,f->name)){*f->result=*e;f->found=true;return false;}return true;}
int fat32_lookup(struct fat32_volume*v,const char*path,struct fat32_entry*out){if(!v||!path||!out)return-1;while(*path=='/')path++;if(!*path){*out=(struct fat32_entry){.cluster=v->root_cluster,.directory=true};copy(out->name,"/",sizeof(out->name));return 0;}uint32_t directory=v->root_cluster;char component[256];for(;;){size_t n=0;while(*path&&*path!='/'&&n<255)component[n++]=*path++;component[n]=0;while(*path=='/')path++;struct fat32_entry found;struct find_context context={.name=component,.result=&found};int error=scan_directory(v,directory,find_cb,&context);if(error<0||!context.found)return-1;if(!*path){*out=found;return 0;}if(!found.directory)return-1;directory=found.cluster;}}
int fat32_list(struct fat32_volume*v,const char*path,fat32_list_fn cb,void*c){struct fat32_entry directory;if(fat32_lookup(v,path,&directory)||!directory.directory)return-1;return scan_directory(v,directory.cluster,cb,c)<0?-1:0;}
long fat32_read(struct fat32_volume*v,const char*path,uint64_t offset,void*buffer,size_t size){struct fat32_entry file;if(fat32_lookup(v,path,&file)||file.directory||offset>file.size)return-1;if(size>file.size-offset)size=file.size-offset;uint64_t cluster_bytes=(uint64_t)v->sectors_per_cluster*512,skip=offset/cluster_bytes,inside=offset%cluster_bytes;uint32_t cluster=file.cluster;while(skip--){if(next_cluster(v,cluster,&cluster)||cluster>=FAT_EOC)return-1;}uint8_t sector[512],*out=buffer;size_t done=0;while(done<size&&cluster<FAT_EOC){for(uint8_t s=0;s<v->sectors_per_cluster&&done<size;s++){if(block_read(v->device,cluster_lba(v,cluster)+s,1,sector))return-1;uint64_t begin=s*512ull;if(inside>=begin+512)continue;unsigned at=inside>begin?(unsigned)(inside-begin):0;for(;at<512&&done<size;at++)out[done++]=sector[at];}inside=0;if(done<size&&next_cluster(v,cluster,&cluster))return-1;}return(long)done;}
static void put16(uint8_t*p,uint16_t v){p[0]=v;p[1]=v>>8;}static void put32(uint8_t*p,uint32_t v){put16(p,v);put16(p+2,v>>16);}
static void make_entry(uint8_t*e,const char name[11],uint8_t attr,uint32_t cluster,uint32_t size){for(unsigned i=0;i<32;i++)e[i]=0;for(unsigned i=0;i<11;i++)e[i]=(uint8_t)name[i];e[11]=attr;put16(e+20,cluster>>16);put16(e+26,cluster);put32(e+28,size);}
static bool count_cb(const struct fat32_entry*e,void*c){(void)e;(*(unsigned*)c)++;return true;}
bool fat32_self_test(struct block_device*d){if(!d||d->readonly||d->sectors<4096)return false;uint8_t b[512];for(unsigned i=0;i<512;i++)b[i]=0;b[0]=0xeb;b[1]=0x58;b[2]=0x90;put16(b+11,512);b[13]=1;put16(b+14,32);b[16]=1;put32(b+32,4096);put32(b+36,32);put32(b+44,2);b[510]=0x55;b[511]=0xaa;if(block_write(d,0,1,b))return false;for(unsigned i=0;i<512;i++)b[i]=0;put32(b,0x0ffffff8);put32(b+4,0xffffffff);put32(b+8,0x0fffffff);put32(b+12,0x0fffffff);put32(b+16,0x0fffffff);put32(b+20,0x0fffffff);if(block_write(d,32,1,b))return false;for(unsigned i=0;i<512;i++)b[i]=0;make_entry(b,"HELLO   TXT",0x20,3,12);make_entry(b+32,"SUBDIR     ",0x10,4,0);if(block_write(d,64,1,b))return false;for(unsigned i=0;i<512;i++)b[i]=0;const char*hello="HELLO AXIOM\n";for(unsigned i=0;hello[i];i++)b[i]=hello[i];if(block_write(d,65,1,b))return false;for(unsigned i=0;i<512;i++)b[i]=0;make_entry(b,"NESTED  TXT",0x20,5,7);if(block_write(d,66,1,b))return false;for(unsigned i=0;i<512;i++)b[i]=0;const char*nested="STORAGE";for(unsigned i=0;nested[i];i++)b[i]=nested[i];if(block_write(d,67,1,b)||block_flush(d))return false;struct fat32_volume v;if(fat32_open(&v,d,0))return false;struct fat32_entry e;if(fat32_lookup(&v,"/hello.txt",&e)||e.size!=12||fat32_lookup(&v,"/subdir/nested.txt",&e))return false;char out[16]={0};if(fat32_read(&v,"/subdir/nested.txt",0,out,7)!=7)return false;for(unsigned i=0;i<7;i++)if(out[i]!=nested[i])return false;unsigned count=0;if(fat32_list(&v,"/",count_cb,&count)||count!=2)return false;return true;}
