#include "vfs.h"
#include "memory.h"
#include "hardware.h"
#define NODE_MAX 256
#define FD_MAX 32
#define NAME_MAX 47
#define PATH_MAX 255
#define FILE_MAX (1024u*1024u)
struct node{bool used,directory,symlink,hardlink,locked,mounted,readonly;char name[48],target[256];int parent,backing;uint8_t*pages[256];uint64_t size,capacity,created,modified,quota;uint32_t uid,gid,mode,links;char type[12],source[32];};
struct descriptor{bool used;int node;uint64_t offset;uint32_t flags;};
static struct node nodes[NODE_MAX];static struct descriptor fds[FD_MAX];static char cwd[PATH_MAX+1]="/";static uint32_t current_uid,current_gid;static uint64_t quotas[16];
static size_t slen(const char*s){size_t n=0;while(s[n])n++;return n;}static bool seq(const char*a,const char*b){while(*a&&*a==*b){a++;b++;}return!*a&&!*b;}static void scopy(char*d,const char*s,size_t n){if(!n)return;while(*s&&n>1){*d++=*s++;n--;}*d=0;}
static uint64_t now(void){return hardware_uptime_ms()/1000;}
static struct node*content(int n){unsigned hops=0;while(nodes[n].hardlink&&hops++<NODE_MAX)n=nodes[n].backing;return&nodes[n];}
static bool access_ok(const struct node*n,uint32_t bit){if(current_uid==0)return true;uint32_t bits=current_uid==n->uid?(n->mode>>6):(current_gid==n->gid?(n->mode>>3):n->mode);return !!(bits&bit);}
static int child(int parent,const char*name){for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].parent==parent&&seq(nodes[i].name,name))return i;return VFS_ENOENT;}
static int resolve(const char*path,bool follow){if(!path||!*path)return VFS_EINVAL;int at=0;const char*p=path;if(*p=='/')p++;else{at=0;const char*c=cwd+1;char part[48];while(*c){size_t n=0;while(*c&&*c!='/'&&n<47)part[n++]=*c++;part[n]=0;if(*c)c++;if(n){if(!access_ok(&nodes[at],1))return VFS_EACCES;at=child(at,part);if(at<0)return at;}}}char part[48];while(*p){while(*p=='/')p++;if(!*p)break;size_t n=0;while(*p&&*p!='/'&&n<47)part[n++]=*p++;part[n]=0;if(*p&&*p!='/')return VFS_ENAMETOOLONG;if(seq(part,"."))continue;if(seq(part,"..")){if(at)at=nodes[at].parent;continue;}if(!nodes[at].directory)return VFS_ENOTDIR;if(!access_ok(&nodes[at],1))return VFS_EACCES;at=child(at,part);if(at<0)return at;}if(follow&&nodes[at].symlink)return resolve(nodes[at].target,false);return at;}
static int parent_of(const char*path,char*name){char temp[PATH_MAX+1];scopy(temp,path,sizeof(temp));size_t n=slen(temp);while(n>1&&temp[n-1]=='/')temp[--n]=0;char*slash=0;for(char*p=temp;*p;p++)if(*p=='/')slash=p;if(!slash){scopy(name,temp,48);return resolve(cwd,true);}scopy(name,slash+1,48);if(slen(slash+1)>NAME_MAX)return VFS_ENAMETOOLONG;if(slash==temp)slash[1]=0;else*slash=0;return resolve(temp,true);}
static int create(const char*path,bool directory,uint32_t mode){char name[48];int parent=parent_of(path,name);if(parent<0)return parent;if(!nodes[parent].directory)return VFS_ENOTDIR;if(nodes[parent].readonly)return VFS_EROFS;if(!access_ok(&nodes[parent],3))return VFS_EACCES;if(!*name)return VFS_EINVAL;if(child(parent,name)>=0)return VFS_EEXIST;for(int i=1;i<NODE_MAX;i++)if(!nodes[i].used){nodes[i]=(struct node){.used=true,.directory=directory,.parent=parent,.created=now(),.modified=now(),.mode=mode,.links=1,.quota=FILE_MAX,.uid=current_uid,.gid=current_gid};scopy(nodes[i].name,name,sizeof(nodes[i].name));return i;}return VFS_ENOSPC;}
void vfs_init(void){current_uid=current_gid=0;for(int i=0;i<NODE_MAX;i++)nodes[i].used=false;for(unsigned i=0;i<16;i++)quotas[i]=FILE_MAX;nodes[0]=(struct node){.used=true,.directory=true,.parent=0,.mode=0755,.links=1,.quota=FILE_MAX};const char*dirs[]={"/boot","/system","/apps","/users","/users/admin","/tmp","/var","/devices","/var/log"};for(unsigned i=0;i<sizeof(dirs)/sizeof(dirs[0]);i++)vfs_mkdir(dirs[i],i==3?0755:(i==4?0700:(i==5?01777:0755)));}
int vfs_open(const char*path,uint32_t flags){int n=resolve(path,true);if(n<0&&(flags&VFS_CREATE))n=create(path,false,0644);if(n<0)return n;struct node*c=content(n);if(c->directory&&!(flags&VFS_DIRECTORY))return VFS_EISDIR;if((flags&VFS_READ)&&!access_ok(c,4))return VFS_EACCES;if((flags&VFS_WRITE)&&!access_ok(c,2))return VFS_EACCES;if((flags&VFS_WRITE)&&(c->readonly||c->locked))return c->locked?VFS_EBUSY:VFS_EROFS;if((flags&VFS_TRUNCATE)&&(flags&VFS_WRITE)){for(unsigned p=0;p<256;p++)if(c->pages[p]){kfree(c->pages[p]);c->pages[p]=0;}c->size=c->capacity=0;c->modified=now();}for(int i=0;i<FD_MAX;i++)if(!fds[i].used){fds[i]=(struct descriptor){.used=true,.node=n,.flags=flags};return i;}return VFS_ENOSPC;}
int vfs_close(int fd){if(fd<0||fd>=FD_MAX||!fds[fd].used)return VFS_EBADF;fds[fd].used=false;return 0;}
long vfs_read(int fd,void*b,size_t size){if(fd<0||fd>=FD_MAX||!fds[fd].used)return VFS_EBADF;struct descriptor*f=&fds[fd];struct node*n=content(f->node);if(n->directory)return VFS_EISDIR;if(f->offset>=n->size)return 0;if(size>n->size-f->offset)size=n->size-f->offset;uint8_t*d=b;for(size_t i=0;i<size;i++){uint64_t pos=f->offset+i;d[i]=n->pages[pos/4096]?n->pages[pos/4096][pos%4096]:0;}f->offset+=size;return size;}
uint64_t vfs_user_usage(uint32_t uid){uint64_t total=0;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&!nodes[i].hardlink&&nodes[i].uid==uid)total+=nodes[i].capacity;return total;}
long vfs_write(int fd,const void*b,size_t size){if(fd<0||fd>=FD_MAX||!fds[fd].used)return VFS_EBADF;struct descriptor*f=&fds[fd];struct node*n=content(f->node);if(!(f->flags&VFS_WRITE))return VFS_EACCES;if(n->readonly)return VFS_EROFS;if(f->offset+size>n->quota)return VFS_EDQUOT;if(f->offset+size>FILE_MAX)return VFS_ENOSPC;uint64_t first=f->offset/4096,last=size?(f->offset+size-1)/4096:first,new_pages=0;for(uint64_t p=first;p<=last;p++)if(!n->pages[p])new_pages++;uint64_t limit=n->uid<16?quotas[n->uid]:FILE_MAX;if(vfs_user_usage(n->uid)+new_pages*4096>limit)return VFS_EDQUOT;for(uint64_t p=first;p<=last;p++)if(!n->pages[p]){n->pages[p]=kmalloc(4096);if(!n->pages[p])return VFS_ENOSPC;for(unsigned x=0;x<4096;x++)n->pages[p][x]=0;n->capacity+=4096;}const uint8_t*s=b;for(size_t i=0;i<size;i++){uint64_t pos=f->offset+i;n->pages[pos/4096][pos%4096]=s[i];}f->offset+=size;if(f->offset>n->size)n->size=f->offset;n->modified=now();return size;}
long vfs_seek(int fd,uint64_t o){if(fd<0||fd>=FD_MAX||!fds[fd].used)return VFS_EBADF;fds[fd].offset=o;return o;}
int vfs_mkdir(const char*p,uint32_t m){int n=create(p,true,m);return n<0?n:0;}
static void release_content(struct node*n){for(unsigned p=0;p<256;p++)if(n->pages[p]){kfree(n->pages[p]);n->pages[p]=0;}n->capacity=0;}
static void remove_tree(int n){for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].parent==n)remove_tree(i);if(nodes[n].hardlink){struct node*t=content(n);if(t->links)t->links--;}else if(nodes[n].links>1){int promote=-1;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].hardlink&&nodes[i].backing==n){promote=i;break;}if(promote>=0){char name[48];int parent=nodes[promote].parent;scopy(name,nodes[promote].name,sizeof(name));nodes[promote]=nodes[n];nodes[promote].parent=parent;scopy(nodes[promote].name,name,sizeof(nodes[promote].name));nodes[promote].links--;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].hardlink&&nodes[i].backing==n)nodes[i].backing=promote;}else release_content(&nodes[n]);}else release_content(&nodes[n]);nodes[n].used=false;}
int vfs_unlink(const char*p,bool recursive){int n=resolve(p,false);if(n<=0)return n?n:VFS_EINVAL;if(!access_ok(&nodes[nodes[n].parent],3))return VFS_EACCES;if(nodes[n].locked)return VFS_EBUSY;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].parent==n&&!recursive)return VFS_EBUSY;remove_tree(n);return 0;}
int vfs_rename(const char*a,const char*b){int n=resolve(a,false);if(n<0)return n;char name[48];int parent=parent_of(b,name);if(parent<0)return parent;if(!access_ok(&nodes[nodes[n].parent],3)||!access_ok(&nodes[parent],3))return VFS_EACCES;if(nodes[n].locked)return VFS_EBUSY;if(child(parent,name)>=0)return VFS_EEXIST;nodes[n].parent=parent;scopy(nodes[n].name,name,48);nodes[n].modified=now();return 0;}
int vfs_link(const char*t,const char*l,bool symbolic){int target=resolve(t,true);if(target<0)return target;int n=create(l,false,0777);if(n<0)return n;if(symbolic){nodes[n].symlink=true;scopy(nodes[n].target,t,256);}else{struct node*c=content(target);if(c->directory){nodes[n].used=false;return VFS_EISDIR;}nodes[n].hardlink=true;nodes[n].backing=(int)(c-nodes);c->links++;nodes[n].links=c->links;}return 0;}
static void fill(int n,struct vfs_stat*s){struct node*c=content(n);*s=(struct vfs_stat){.size=c->size,.allocated=c->capacity,.created=c->created,.modified=c->modified,.uid=c->uid,.gid=c->gid,.mode=c->mode,.links=c->links,.directory=c->directory,.symlink=nodes[n].symlink,.sparse=c->capacity<((c->size+4095)&~4095ull)};}
int vfs_stat_path(const char*p,struct vfs_stat*s){int n=resolve(p,false);if(n<0)return n;fill(n,s);return 0;}
int vfs_list(const char*p,vfs_list_fn cb,void*c){int n=resolve(p,true);if(n<0)return n;if(!nodes[n].directory)return VFS_ENOTDIR;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&nodes[i].parent==n){struct vfs_stat s;fill(i,&s);cb(nodes[i].name,&s,c);}return 0;}
int vfs_chmod(const char*p,uint32_t m){int n=resolve(p,true);if(n<0)return n;struct node*c=content(n);if(current_uid&&current_uid!=c->uid)return VFS_EACCES;c->mode=m&07777;return 0;}int vfs_chown(const char*p,uint32_t u,uint32_t g){int n=resolve(p,true);if(n<0)return n;if(current_uid)return VFS_EACCES;struct node*c=content(n);c->uid=u;c->gid=g;return 0;}
void vfs_set_credentials(uint32_t uid,uint32_t gid){current_uid=uid;current_gid=gid;}int vfs_lock(const char*p,bool locked){int n=resolve(p,true);if(n<0)return n;struct node*c=content(n);if(current_uid&&current_uid!=c->uid)return VFS_EACCES;c->locked=locked;return 0;}int vfs_set_quota(uint32_t uid,uint64_t bytes){if(current_uid||uid>=16)return VFS_EACCES;quotas[uid]=bytes;return 0;}
static void make_path(int n,char*out,size_t cap){if(n==0){scopy(out,"/",cap);return;}int chain[NODE_MAX],count=0;while(n&&count<NODE_MAX){chain[count++]=n;n=nodes[n].parent;}size_t at=0;out[at++]='/';for(int i=count-1;i>=0;i--){for(size_t j=0;nodes[chain[i]].name[j]&&at+1<cap;j++)out[at++]=nodes[chain[i]].name[j];if(i&&at+1<cap)out[at++]='/';}out[at]=0;}
int vfs_chdir(const char*p){int n=resolve(p,true);if(n<0)return n;if(!nodes[n].directory)return VFS_ENOTDIR;if(!access_ok(&nodes[n],1))return VFS_EACCES;make_path(n,cwd,sizeof(cwd));return 0;}const char*vfs_cwd(void){return cwd;}
int vfs_mount(const char*s,const char*p,const char*t,bool ro){int n=resolve(p,true);if(n<0)return n;if(nodes[n].mounted)return VFS_EBUSY;nodes[n].mounted=true;nodes[n].readonly=ro;scopy(nodes[n].source,s,32);scopy(nodes[n].type,t,12);return 0;}int vfs_unmount(const char*p){int n=resolve(p,true);if(n<0)return n;if(!nodes[n].mounted)return VFS_EINVAL;nodes[n].mounted=false;nodes[n].readonly=false;return 0;}
uint64_t vfs_used_bytes(void){uint64_t n=0;for(int i=0;i<NODE_MAX;i++)if(nodes[i].used)n+=nodes[i].capacity;return n;}uint64_t vfs_capacity_bytes(void){return (uint64_t)NODE_MAX*FILE_MAX;}
int vfs_check(bool repair){(void)repair;for(int i=1;i<NODE_MAX;i++)if(nodes[i].used&&(!nodes[nodes[i].parent].used||!nodes[nodes[i].parent].directory||(nodes[i].hardlink&&(!nodes[i].backing||!nodes[nodes[i].backing].used))))return VFS_EIO;return 0;}
const char*vfs_error_string(int e){switch(e){case 0:return"OK";case VFS_ENOENT:return"NOT FOUND";case VFS_EACCES:return"PERMISSION DENIED";case VFS_EBUSY:return"BUSY";case VFS_EEXIST:return"ALREADY EXISTS";case VFS_ENOTDIR:return"NOT A DIRECTORY";case VFS_EISDIR:return"IS A DIRECTORY";case VFS_ENOSPC:return"NO SPACE";case VFS_EROFS:return"READ ONLY";case VFS_ENAMETOOLONG:return"NAME TOO LONG";case VFS_EDQUOT:return"QUOTA EXCEEDED";default:return"INVALID OR I/O ERROR";}}
bool vfs_self_test(void){bool ok=true;vfs_set_credentials(0,0);int fd=vfs_open("/tmp/sparse",VFS_CREATE|VFS_WRITE);char text[5]={'A','X','I','O','M'};if(fd<0)ok=false;else{vfs_seek(fd,8192);if(vfs_write(fd,text,5)!=5)ok=false;vfs_close(fd);}struct vfs_stat st;if(vfs_stat_path("/tmp/sparse",&st)||!st.sparse||st.size!=8197||st.allocated!=4096)ok=false;if(vfs_link("/tmp/sparse","/tmp/hard",false))ok=false;fd=vfs_open("/tmp/hard",VFS_WRITE);if(fd<0)ok=false;else{vfs_seek(fd,8192);char x='X';if(vfs_write(fd,&x,1)!=1)ok=false;vfs_close(fd);}if(vfs_unlink("/tmp/sparse",false))ok=false;fd=vfs_open("/tmp/hard",VFS_READ);if(fd<0)ok=false;else{vfs_seek(fd,8192);char x=0;if(vfs_read(fd,&x,1)!=1||x!='X')ok=false;vfs_close(fd);}if(vfs_lock("/tmp/hard",true)||vfs_open("/tmp/hard",VFS_WRITE)!=VFS_EBUSY||vfs_lock("/tmp/hard",false))ok=false;fd=vfs_open("/tmp/private",VFS_CREATE|VFS_WRITE);if(fd>=0)vfs_close(fd);if(vfs_chmod("/tmp/private",0600))ok=false;vfs_set_credentials(1,1);if(vfs_open("/tmp/private",VFS_READ)!=VFS_EACCES)ok=false;vfs_set_credentials(0,0);if(vfs_set_quota(1,4096))ok=false;vfs_set_credentials(1,1);fd=vfs_open("/tmp/quota",VFS_CREATE|VFS_WRITE);if(fd<0)ok=false;else{char one=1;if(vfs_write(fd,&one,1)!=1)ok=false;vfs_seek(fd,4096);if(vfs_write(fd,&one,1)!=VFS_EDQUOT)ok=false;vfs_close(fd);}vfs_set_credentials(0,0);vfs_unlink("/tmp/hard",false);vfs_unlink("/tmp/private",false);vfs_unlink("/tmp/quota",false);return ok&&vfs_check(false)==0;}
